---
# tasks file for roles/apache
- name: Installer Apache (Amazon Linux)
  dnf:
    name: httpd
    state: present
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Copier la page personnalisée
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify: Restart Apache

- name: assurer que Apache est actif
  service:
    name: httpd
    state: started
    enabled: yes